### ISSUE TITLE
Gap between forge and github version

### ISSUE THREAD

**Issue by dthielking** [voxpupuli/puppet-dhcp#104]
Hey,
why is there a huge gap between release version on https://forge.puppet.com/puppetlabs/dhcp (V0.4.0) and github release (1.0.0)

**Comment by domcleal** [comment]
The module is published in the VoxPupuli namespace at https://forge.puppet.com/puppet/dhcp rather than in Puppet Labs', it was migrated.

**Comment by dthielking** [comment]
Perfect thanks for helping!

**Comment by mgla** [comment]
Could you add a notice similarly to the old version of the [voxpopuli/zabbix module](https://forge.puppet.com/wdijkerman/zabbix)?
