### ISSUE TITLE
Insert possibility to enable host declaration without IP.

### ISSUE THREAD

**Issue by dthielking** [voxpupuli/puppet-dhcp#106]
Causes distributing IP-Addresses just to known clients but without fixed address.

Maybe code like this:
`
<% if @ip != '' -%>
    ip address "<%= @ip %>";
<% end -%>
`

**Comment by mergwyn** [comment]
I've got a similar requirement. I often use dhcp to allocate hostnames or to distribute other options (eg routers) where I don't care about the IP address.  I tried similar code to the above, but (using hiera) I received a message when I did not include an IP address:

`Evaluation Error: Error while evaluating a Resource Statement, Dhcp::Host[LGwebOSTV]: expects a value for parameter 'ip' (file: /etc/puppetlabs/code/environments/production/modules/dhcp/manifests/init.pp, line: 289)` 

I can workaround this by setting the IP address to 0.0.0.0 and then ignoring it in the template but this seems like a kludge!  Any suggestions?
