### ISSUE TITLE
Docs: mention the ripienaar-concat dependency

### ISSUE THREAD

**Issue by mattiasgeniar** [voxpupuli/puppet-dhcp#11]
default behaviour when following the README:

<pre># puppet apply /etc/puppet/manifests/razor.pp --verbose --noop
info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/root_home.rb
info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/puppet_vardir.rb
Could not find class concat::setup for puppet-razor at /etc/puppet/modules/dhcp/manifests/init.pp:84 on node puppet-razor</pre>

After a 'puppet module install ripienaar-concat' the 'concat::setup' is correctly available.

**Comment by juniorsysadmin** [comment]
No longer appears to be the case, closing.
