### ISSUE TITLE
No dependency on Module Concat

### ISSUE THREAD

**Issue by pjfoley** [voxpupuli/puppet-dhcp#17]
Hi,

Just walking through a howto to setup Razor and as part of this process installed the puppetlabs-dhcp.  This has a clean install of puppet and puppetmaster.  Following the guide these are the commands I have run:

puppet module install puppetlabs-razor
puppet apply /etc/puppet/modules/razor/tests/init.pp --verbose

puppet module install zleslie/dhcp
puppet apply /etc/puppet/modules/dhcp/tests/init.pp --verbose

Running the dhcp tests init.pp file it complains that it could not find class concat::setup.

I think the forge module file needs to include a dependacy on concat::setup.

Peter

**Comment by juniorsysadmin** [comment]
No longer appears to be the case, closing. (Newer version will be published to the Forge soon if it hasn't been already)
