### ISSUE TITLE
Could not find dependent Service[dhcpd] for File[/etc/systemd/system/dhcpd.service] when manage_service is false

### ISSUE THREAD

**Issue by danyel2014** [voxpupuli/puppet-dhcp#170]
Hi all, 

while trying to use this module in combination with pacemaker, I've discovered that if manage_service is false, then File[/etc/systemd/system/dhcpd.service] cannot "notify" the Service['dhcpd'].

Error: Failed to apply catalog: Could not find dependent Service[dhcpd] for File[/etc/systemd/system/dhcpd.service] at /opt/mdc/puppet/puppet_3rd_party/modules/dhcp/manifests/init.pp:181

FIX:

```diff
diff --git manifests/init.pp manifests/init.pp
index 23ac4f3..0d56344 100644
--- manifests/init.pp
+++ manifests/init.pp
@@ -183,7 +183,7 @@ class dhcp (
       owner   => 'root',
       group   => 'root',
       mode    => '0644',
-      notify  => Service[$servicename],
+      notify  => $service_notify_real,
       content => template('dhcp/dhcpd.service'),
     }
   } else {
```

In the end, thank you for the great job
Dan

**Comment by ekohl** [comment]
Hi @danyel2014. Since you already have the fix, would you be able to come up with a PR? That'd give you proper credit in the changelogs and git history.
