### ISSUE TITLE
Tests - Pool has a string not an array

### ISSUE THREAD

**Issue by pjfoley** [voxpupuli/puppet-dhcp#18]
Hi,

When I installed the this module I ran the test script and got the below output:

root@creator ~# puppet apply /etc/puppet/modules/dhcp/tests/init.pp --verbose
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/pe_version.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/root_home.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/puppet_vardir.rb
Info: Loading facts in /etc/puppet/modules/stdlib/lib/facter/facter_dot_d.rb
Info: Loading facts in /etc/puppet/modules/concat/lib/facter/concat_basedir.rb
Warning: Config file /etc/puppet/hiera.yaml not found, using Hiera defaults
Error: Failed to parse template dhcp/dhcpd.pool.erb:
  Filepath: /etc/puppet/modules/dhcp/templates/dhcpd.pool.erb
  Line: 7
  Detail: undefined method `each' for "10.1.1.100":String
 at /etc/puppet/modules/dhcp/manifests/pool.pp:15 on node creator.mgnt.local
Error: Failed to parse template dhcp/dhcpd.pool.erb:
  Filepath: /etc/puppet/modules/dhcp/templates/dhcpd.pool.erb
  Line: 7
  Detail: undefined method `each' for "10.1.1.100":String
 at /etc/puppet/modules/dhcp/manifests/pool.pp:15 on node creator.mgnt.local

While trying to work out what was wrong I realised that in the tests/init.pp file the test for the dhcpd.pool.erb file is passing a string and not an array:

dhcp::pool{ 'example.com':
  network => '10.1.1.0',
  mask    => '255.255.255.0',
  range   => '10.1.1.100 10.1.1.200',
  gateway => '10.1.1.1',
}

(Look at the range line) which means that in the erb template the string does not have an each method.

Also the DHCP module has a dependency on the Bind Module which means that the test fails because it cannot find the Bind module.

**Comment by alexjfisher** [comment]
It looks like this was fixed in https://github.com/voxpupuli/puppet-dhcp/commit/0bf424a60a69db612f8c4264c48528118a4e9760

`range` now accepts a string or an array of strings.
