### ISSUE TITLE
in pool manifest, for options, an array is allowed but fails

### ISSUE THREAD

**Issue by Rocco83** [voxpupuli/puppet-dhcp#266]
Hi,

In the pool.pp manifest, the options is referred as:
https://github.com/voxpupuli/puppet-dhcp/blob/86a6553d42a14e9d5d892b86f28fb9fca3ed1ae2/manifests/pool.pp#L29

But, in the code, is reported as follows:

https://github.com/voxpupuli/puppet-dhcp/blob/86a6553d42a14e9d5d892b86f28fb9fca3ed1ae2/manifests/pool.pp#L74

Given the YAML
```
    options:
      - 'netbios-name-servers 192.168.0.1'
      - 'netbios-dd-server 192.168.0.1'
      - 'netbios-node-type 8'
      - 'ubnt.unifi-address 192.168.0.2'
```

It is producing the following error:
```
Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Dhcp::Pool[DOMAIN]: parameter 'options' expects a value of type Undef or String, got Tuple (file: /etc/puppetlabs/code/environments/development/modules/dhcp/manifests/init.pp, line: 311) on node FQDN
```

The following line restore the functionality:
`  Optional[Array[String]] $options              = undef,`
As well as
`Optional[Variant[Array[String],String[1]]] $options              = undef,`

Mind that also "parameter" can be an Array, so i believe it's broken as well.
https://github.com/voxpupuli/puppet-dhcp/blob/86a6553d42a14e9d5d892b86f28fb9fca3ed1ae2/manifests/pool.pp#L32
https://github.com/voxpupuli/puppet-dhcp/blob/86a6553d42a14e9d5d892b86f28fb9fca3ed1ae2/manifests/pool.pp#L75

Are possibly other portion of code with the same mistake?

Before pushing a PR, i would like to get a review...

**Comment by ekohl** [comment]
I think you're right. It was introduced in e303edbd0256228338b414350b313c5a3cdc3bcb but this doesn't match what the template accepts. Please submit a PR for this.
