### ISSUE TITLE
Question on support for Puppet 8

### ISSUE THREAD

**Issue by maureen-lawless** [voxpupuli/puppet-dhcp#277]
Hi,

Is there a plan to release a version of this module that is compatible with Puppet 8?

Currently in metadata.json the version requirements on Puppet are as following: ">= 7.0.0 < 8.0.0"
The concat and stdlib versions would also need to be incremented.

Thanks,
Maureen

**Comment by ekohl** [comment]
https://github.com/voxpupuli/puppet-dhcp/pull/276 is now failing, so that needs to be sorted out. https://github.com/voxpupuli/puppet-dhcp/pull/275 would allow the newer stdlib.

**Comment by maureen-lawless** [comment]
OK, thank you. 
Looks like the concat module requirements also need to move from supporting versions < 8 to versions < 9 or < 10.
