### ISSUE TITLE
Add pools/hosts parameters for create_resources()

### ISSUE THREAD

**Issue by domcleal** [voxpupuli/puppet-dhcp#91]
The `dhcp` class should have pools and hosts parameters which use create_resources() to instantiate a number of DHCP pools and hosts defines, to help when using the module from Hiera or an ENC.

Based on https://github.com/theforeman/puppet-dhcp/commit/447898e425c133bf02efd8bad7eba981abd1bd6a.

**Comment by ekohl** [comment]
I believe this was fixed through https://github.com/voxpupuli/puppet-dhcp/pull/146 and can be closed.
